### ISSUE TITLE
A couple of typos in 02_1_Indexing and Slicing.ipynb

### ISSUE THREAD

**Issue by chekunkov** [leriomaggio/numpy_ep2015#1]
Hey, just spotted a couple of typos in your notebook - I believe you should use `np.arange` and `np.mean` there

<img width="970" alt="numpy_training_02_1_indexing_and_slicing_ipynb_at_master_ _leriomaggio_numpy_training" src="https://cloud.githubusercontent.com/assets/744331/8799164/6a846600-2fa8-11e5-8eef-13408ab4f781.png">

**Comment by leriomaggio** [comment]
Thanks a lot! I'm gonna fix them all soon and update the notebooks!

**Comment by leriomaggio** [comment]
Fixed !-)
