### ISSUE TITLE
Add a note about integer overflow

### ISSUE THREAD

**Issue by chekunkov** [leriomaggio/numpy_ep2015#3]
I would be nice to add some note about possible integer overflow in numpy arrays in `02_Introduction to Numpy`, maybe after `Conversions and Type Casting` header. Here I created a gist to reproduce integer overflow in numpy arrays: https://gist.github.com/chekunkov/5fd5c2c7b0589ddf3d16

**Comment by leriomaggio** [comment]
Added in the latest commit!

Thanks again for the suggestion :+1:
